version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress_app
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: wordpress_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dwes
      MYSQL_USER: dwes
      MYSQL_PASSWORD: dwes
    volumes:
      - db_data:/var/lib/mysql

volumes:
  wordpress_data:
  db_data:
