# Usar la imagen oficial de PHP con Apache
FROM php:7.4-apache

# Instalar la extensión mysqli (necesaria para MySQL)
RUN docker-php-ext-install mysqli

# Habilitar módulos de Apache (opcional, dependiendo del proyecto)
RUN a2enmod rewrite

# Copiar los archivos del proyecto al directorio de Apache
COPY ./app /var/www/html

# Establecer permisos (opcional, dependiendo de los requisitos del proyecto)
RUN chown -R www-data:www-data /var/www/html \
    && chmod -R 755 /var/www/html
