version: '3.8'

services:
  php:
    build: .
    container_name: php_app
    ports:
      - "8081:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: php_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dwes
      MYSQL_USER: dwes
      MYSQL_PASSWORD: dwes
    volumes:
      - db_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db

volumes:
  db_data:
